//Values below are just for initialising and will be changed when synth is initialised to current panel controls & EEPROM settings
byte midiChannel = MIDI_CHANNEL_OMNI;//(EEPROM)
String patchName = INITPATCHNAME;
boolean encCW = true;
int oldfilterLogLin = 0;
int oldampLogLin = 0;
int oldmidiChannel = 0;
int oldAfterTouchDest = 0;
int oldNotePriority = 0;
int oldFilterLoop = 0;
int oldAmpLoop = 0;
int oldClockSource = 0;
int oldafterTouchDepth = 0;
int afterTouchDepth = 0;
int NotePriority = 1;
int FilterLoop = 0;
int AmpLoop = 0;
int ClockSource = 0;

// polykit parameters in order of mux

float osc1Tune = 0;
float osc1Tunestr = 0; // for display
float fmDepth = 0;
float fmDepthstr = 0;
float osc2Tune = 0;
float osc2Tunestr = 0;
float osc1WaveMod = 0;
float osc1WaveModstr = 0;
float osc2WaveMod = 0;
float osc2WaveModstr = 0;
float osc1WaveSelect = 0;
float osc1WaveSelectstr = 0;
float osc1Range = 0;
float osc1Rangestr = 0;
float oct1A = 0;
float oct1B = 0;
float osc2Range = 0;
float osc2Rangestr = 0;
float oct2A = 0;
float oct2B = 0;
float osc2WaveSelect = 0;
float osc2WaveSelectstr = 0;
float osc1WaveA = 0;
float osc1WaveB = 0;
float osc1WaveC = 0;
float osc2WaveA = 0;
float osc2WaveB = 0;
float osc2WaveC = 0;
float glideTime = 0;
float glideTimestr = 0;
float noiseLevel = 0;
float noiseLevelstr = 0; // for display
float osc2Levelstr = 0; //for display
float osc2Level = 0;
float osc1Level = 0; // for display
float osc1Levelstr = 0;
float fmWaveDepth = 0;
float fmWaveDepthstr = 0; // for display

float filterCutoff = 0;
float oldfilterCutoff = 0;
float filterCutoffstr = 0; // for display
float filterLFO = 0;
float filterLFOstr = 0; // for display
float filterRes = 0;
float filterResstr = 0;
float filterType = 0;
float filterA = 0;
float filterB = 0;
float filterC = 0;
float filterEGlevel = 0;
float filterEGlevelstr = 0;
float LFORate = 0;
float LFORatestr = 0; //for display
String StratusLFOWaveform = "                ";
float LFOWaveform = 0;
float filterAttack = 0;
float filterAttackstr = 0;
float filterDecay = 0;
float filterDecaystr = 0;
float filterSustain = 0;
float filterSustainstr = 0;
float filterRelease = 0;
float filterReleasestr = 0;
float ampAttack = 0;
float ampAttackstr = 0;
float ampDecay = 0;
float ampDecaystr = 0;
float ampSustain = 0;
float ampSustainstr = 0;
float ampRelease = 0;
float ampReleasestr = 0;
float volumeControl = 0;
float volumeControlstr = 0; // for display
float keyTrack = 0;
float keyTrackstr = 0;

int osc1BankA = 0;
int vcaLoop = 0;
int osc1BankB = 0;
int osc2BankA = 0;
int osc2BankB = 0;
int lfoAlt = 0;
int filterPoleSW = 0;
int filterLoop = 0;
int filterEGinv = 0;
int PitchBendLevel = 0;
int PitchBendLevelstr = 0; // for display
int modWheelDepth = 0;
float modWheelLevel = 0;
float modWheelLevelstr = 0;
int filterLogLin = 0;
int ampLogLin = 0;
float afterTouch = 0;
int AfterTouchDest = 0;
float masterTune = 511;

int returnvalue = 0;
